#!/bin/sh -e

if ! getent group alerta >/dev/null; then
    echo Adding group: alerta.
    addgroup --system alerta
fi

if ! getent passwd alerta >/dev/null; then
    echo Adding system user: alerta.
    adduser --system --ingroup alerta --home /var/run/alerta alerta
    usermod -c "Alerta monitoring system" alerta
    usermod -d "/var/run/alerta" alerta
    usermod -g "alerta" alerta
    usermod -s "/bin/false" alerta
fi

#DEBHELPER#

exit 0
