#!/bin/bash
#
# alert-dynect  Start/stop the Alerter DynECT component
#
# chkconfig: 2345 90 60
# description: Alert DynECT is the DynECT API status check daemon

# Source function library.
. /etc/init.d/functions

OPTIONS=""

RETVAL=0
prog="alert-dynect"
binary=/usr/bin/$prog
pidfile=/var/run/alerta/$prog.pid
lockfile=/var/lock/subsys/$prog

# Source config
if [ -f /etc/sysconfig/$prog ] ; then
    . /etc/sysconfig/$prog
fi

start() {
	[ -x $binary ] || exit 5

	# Check if it is already running
	if [ ! -f $lockfile ]; then
        echo -n $"Starting $prog: "
        daemon --pidfile=$pidfile $binary $OPTIONS
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch $lockfile
	    echo
    else
	    status -p $pidfile $prog
	fi
	return $RETVAL
}

stop() {
        echo -n $"Shutting down $prog: "
	killproc -p $pidfile $binary
	RETVAL=$?
        echo
	[ $RETVAL -eq 0 ] && rm -f $lockfile
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  status)
	status -p $pidfile $prog
	;;
  try-restart|condrestart)
	if status $prog > /dev/null; then
	    stop
	    start
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|condrestart|try-restart|status}"
	exit 2
esac

exit $?
