#!/bin/bash
#
# alert-ganglia	Start/stop the Alerter Ganglia daemon.
#
# chkconfig: 2345 90 60
# description: Alert Ganglia is the Ganglia alert feed server daemon for the alerting system.

# Source function library.
. /etc/init.d/functions

RETVAL=0
prog=$(basename $0)
binary=/opt/alerta/bin/alert-ganglia.py
pidfile=/var/run/alerta/$prog.pid
lockfile=/var/lock/subsys/$prog

case "$prog" in
  alert-ganglia-prod)
	OPTIONS="-p $pidfile -E \"PROD;INFRA\""
	;;
  alert-ganglia-dev) 
	OPTIONS="-p $pidfile -E \"REL;QA;TEST;CODE;DEV;STAGE;LWP\""
	;;
  *)
	OPTIONS="-p $pidfile"
	;;
esac

# Source config
if [ -f /etc/sysconfig/$prog ] ; then
    . /etc/sysconfig/$prog
fi

start() {
	[ -x $binary ] || exit 5

        # Start daemons.
        echo -n $"Starting $prog: "
        daemon "$binary $OPTIONS >/dev/null 2>&1 &"
	RETVAL=$?
        echo
	[ $RETVAL -eq 0 ] && touch $lockfile
	return $RETVAL
}

stop() {
        echo -n $"Shutting down $prog: "
	killproc -p $pidfile $binary
	RETVAL=$?
        echo
	[ $RETVAL -eq 0 ] && rm -f $lockfile
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  status)
	status -p $pidfile $prog
	;;
  try-restart|condrestart)
	if status $prog > /dev/null; then
	    stop
	    start
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|condrestart|try-restart|status}"
	exit 2
esac

exit $?
