#!/usr/bin/env python
########################################
#
# alert-ganglia - Alert Ganglia
#
########################################

import os
import sys

possible_topdir = os.path.normpath(os.path.join(os.path.abspath(sys.argv[0]),
                                                os.pardir,
                                                os.pardir))
if os.path.exists(os.path.join(possible_topdir, 'alerta', '__init__.py')):
    sys.path.insert(0, possible_topdir)

from alerta.common import config
from alerta.common import log as logging
from alerta.ganglia.daemon import GangliaDaemon, Version

LOG = logging.getLogger('alerta.ganglia')
CONF = config.CONF

if __name__ == '__main__':
    config.parse_args(sys.argv[1:], version=Version)
    logging.setup('alerta')
    ganglia = GangliaDaemon('alert-ganglia')
    ganglia.start()

