
import datetime
from collections import OrderedDict

PET_SOURCE_TYPE = OrderedDict([
    ('Platform Firmware',              0x07),  # 00h - 07h
    ('SMI Handler',                    0x0F),  # 08h - 0Fh
    ('ISV System Management Software', 0x17),  # 10h - 17h
    ('Alert ASIC',                     0x1F),  # 18h - 1Fh
    ('IPMI',                           0x27),  # 20h - 27h
    ('BIOS Vendor',                    0x2F),  # 28h - 2Fh
    ('System Board Set Vendor',        0x37),  # 30h - 37h
    ('System Integrator',              0x3F),  # 38h - 3Fh
    ('Third Party Add-in',             0x47),  # 40h - 47h
    ('OSV',                            0x4F),  # 48h - 4Fh
    ('NIC',                            0x57),  # 50h - 57h
    ('System Management Card',         0x5F),  # 58h - 5Fh
    ('unspecified',                    0xFF)   # 60h - FFh
])

PET_SEVERITY = {
    '00': 'unspecified',
    '01': 'Monitor',
    '02': 'Information',
    '04': 'OK (return to OK condition)',
    '08': 'Non-critical condition',
    '10': 'Critical condition',
    '20': 'Non-recoverable condition',
}

ENTITY_ID_MAP = {
    '00': 'unspecified',
    '01': 'other',
    '02': 'unknown',
    '03': 'processor',
    '04': 'disk or disk bay',
    '05': 'peripheral bay',
    '06': 'system management module',
    '07': 'system board',
    '08': 'memory module',
    '09': 'processor module',
    '0A': 'power supply',
    '0B': 'add-in card',
    '0C': 'front panel board (control panel)',
    '0D': 'back panel board',
    '0E': 'power system board',
    '0F': 'drive backplane',
    '10': 'system internal expansion board',
    '11': 'other system board',
    '12': 'processor board',
    '13': 'power unit/power domain',
    '14': 'power module/DC-to-DC converter',
    '15': 'power management/power distribution board',
    '16': 'chassis back panel board',
    '17': 'system chassis',
    '18': 'sub-chassis',
    '19': 'Other chassis board',
    '1A': 'Disk Drive Bay',
    '1B': 'Peripheral Bay',
    '1C': 'Device Bay',
    '1D': 'fan/cooling device',
    '1E': 'cooling unit',
    '1F': 'cable/interconnect',
    '20': 'memory device',
    '21': 'System Management Software',
    '22': 'System Firmware (BIOS/EFI)',
    '23': 'Operating System',
    '24': 'System Bus',
    '25': 'Group',
    '26': 'Remote (Out of Band) Management Communications Device',
    '27': 'External Environment',
    '28': 'battery',
    '29': 'Processing blade',
    '2A': 'Connectivity switch',
    '2B': 'Processor/memory module',
    '2C': 'I/O module',
    '2D': 'Processor/IO module',
    '2E': 'Management Controller Firmware',
    '2F': 'IPMI Channel',
    '30': 'PCI Bus',
    '31': 'PCI Express Bus',
    '32': 'SCSI Bus (parallel)',
    '33': 'SATA/SAS bus',
    '34': 'Processor/front-side bus',
    '35': 'Real Time Clock (RTC)',
    '36': 'Reserved',
    '37': 'air inlet',
    '40': 'air inlet',
    '41': 'processor/CPU',
    '42': 'baseboard/main system board'

}

SENSOR_TYPE_MAP = {  # See Table 42-3 Sensor Type Codes, IPMI Specification v2 (June 2009)
    0x00: 'reserved',
    0x01: 'Temperature',
    0x02: 'Voltage',
    0x03: 'Current',
    0x04: 'Fan',
    0x05: 'Physical Security (Chassis Intrusion)',
    0x06: 'Platform Security Violation Attempt',
    0x07: 'Processor',
    0x08: 'Power Supply',
    0x09: 'Power Unit',
    0x0A: 'Cooling Device',
    0x0B: 'Other Units-based Sensor',
    0x0C: 'Memory',
    0x0D: 'Drive Slot (Bay)',
    0x0E: 'POST Memory Resize',
    0x0F: 'System Firmware Progress',
    0x10: 'Event Logging Disabled',
    0x11: 'Watchdog 1',
    0x12: 'System Event',
    0x13: 'Critical Interrupt',
    0x14: 'Button/Switch',
    0x15: 'Module/Board',
    0x16: 'Microcontroller/Coprocessor',
    0x17: 'Add-in Card',
    0x18: 'Chassis',
    0x19: 'Chip Set',
    0x1A: 'Other FRU',
    0x1B: 'Cable/Interconnect',
    0x1C: 'Terminator',
    0x1D: 'System Boot/Restart Initiated',
    0x1E: 'Boot Error',
    0x1F: 'OS Boot',
    0x20: 'OS Stop/Shutdown',
    0x21: 'Slot/Connector',
    0x22: 'System ACPI Power State',
    0x23: 'Watchdog 2',
    0x24: 'Platform Alert',
    0x25: 'Entity Presence',
    0x26: 'Monitor ASIC/IC',
    0x27: 'LAN',
    0x28: 'Management Subsystem Health',
    0x29: 'Battery',
    0x2A: 'Session Audit',
    0x2B: 'Version Change',
    0x2C: 'FRU State',
}

PET_EVENT_TRAPNUM = {
    '65792': ('UnderTemperatureWarningLow', 'WARNING', 'Temperature Event', 'Under-Temperature Warning (Lower non-critical, going low)'),
    '65793': ('UnderTemperatureWarningHigh', 'WARNING', 'Temperature Event', 'Under-Temperature Warning (Lower non-critical, going high)'),
    '65794': ('UnderTemperatureCriticalLow', 'CRITICAL', 'Temperature Event', 'Under-Temperature Warning (Lower critical, going low)'),
    '65795': ('UnderTemperatureCriticalHigh', 'CRITICAL', 'Temperature Event', 'Under-Temperature Warning (Lower critical, going high)'),
    '65796': ('UnderTemperatureNonRecoverableLow', 'CRITICAL', 'Temperature Event', 'Under-Temperature Warning (Lower non-recoverable, going low)'),
    '65797': ('UnderTemperatureNonRecoverableHigh', 'CRITICAL', 'Temperature Event', 'Under-Temperature Warning (Lower non-recoverable, going high)'),
    '65798': ('OverTemperatureWarningLow', 'WARNING', 'Temperature Event', 'Over-Temperature Warning (Upper non-critical, going low)'),
    '65799': ('OverTemperatureWarningHigh', 'WARNING', 'Temperature Event', 'Over-Temperature Warning (Upper non-critical, going high)'),
    '65800': ('OverTemperatureCriticalLow', 'CRITICAL', 'Temperature Event', 'Over-Temperature Warning (Upper critical, going low)'),
    '65801': ('OverTemperatureCriticalHigh', 'CRITICAL', 'Temperature Event', 'Over-Temperature Warning (Upper critical, going high)'),
    '65802': ('OverTemperatureNonRecoverableLow', 'CRITICAL', 'Temperature Event', 'Over-Temperature Warning (Upper non-recoverable, going low)'),
    '65803': ('OverTemperatureNonRecoverableHigh', 'CRITICAL', 'Temperature Event', 'Under-Temperature Warning (Upper non-recoverable, going high)'),
    '65920': ('UnderTemperatureWarningLowCleared', 'INFORMATIONAL', 'Temperature Event', 'Under-Temperature Warning (Lower non-critical, going low) Cleared'),
    '65921': ('UnderTemperatureWarningHighCleared', 'INFORMATIONAL', 'Temperature Event', 'Under-Temperature Warning (Lower non-critical, going high)Cleared'),
    '65922': ('UnderTemperatureCriticalLowCleared', 'INFORMATIONAL', 'Temperature Event', 'Under-Temperature Warning (Lower critical, going low)Cleared'),
    '65923': ('UnderTemperatureCriticalHighCleared', 'INFORMATIONAL', 'Temperature Event', 'Under-Temperature Warning (Lower critical, going high) Cleared'),
    '65924': ('UnderTemperatureNonRecoverableLowCleared', 'INFORMATIONAL', 'Temperature Event', 'Under-Temperature Warning (Lower non-recoverable, going low)Cleared'),
    '65925': ('UnderTemperatureNonRecoverableHighCleared', 'INFORMATIONAL', 'Temperature Event', 'Under-Temperature Warning (Lower non-recoverable, going high) Cleared'),
    '65926': ('OverTemperatureWarningLowCleared', 'INFORMATIONAL', 'Temperature Event', 'Over-Temperature Warning (Upper non-critical, going low) Cleared'),
    '65927': ('OverTemperatureWarningHighCleared', 'INFORMATIONAL', 'Temperature Event', 'Over-Temperature Warning (Upper non-critical, going high)Cleared'),
    '65928': ('OverTemperatureCriticalLowCleared', 'INFORMATIONAL', 'Temperature Event', 'Over-Temperature Warning (Upper critical, going low) Cleared'),
    '65929': ('OverTemperatureCriticalHighCleared', 'INFORMATIONAL', 'Temperature Event', 'Over-Temperature Warning (Upper critical, going high)Cleared'),
    '65930': ('OverTemperatureNonRecoverableLowCleared', 'INFORMATIONAL', 'Temperature Event', 'Over-Temperature Warning (Upper non-recoverable, going low)Cleared'),
    '65931': ('OverTemperatureNonRecoverableHighCleared', 'INFORMATIONAL', 'Temperature Event', 'Under-Temperature Warning (Upper non-recoverable, going high) Cleared'),
    '67330': ('GenericCriticalTemperature', 'CRITICAL', 'Temperature Event', 'Generic Critical Temperature Problem (Transition to Critical from less severe)'),
    '67331': ('GenericTemperatureWarning', 'WARNING', 'Temperature Event', 'Generic Temperature Warning (Transition to Warning from less severe)'),
    '131328': ('UnderVoltageWarningLow', 'WARNING', 'Voltage Event', 'Under-Voltage Warning (Lower non-critical, going low)'),
    '131329': ('UnderVoltageWarningHigh', 'WARNING', 'Voltage Event', 'Under-Voltage Warning (Lower non-critical, going high)'),
    '131330': ('UnderVoltageCriticalLow', 'CRITICAL', 'Voltage Event', 'Under-Voltage Warning (Lower critical, going low)'),
    '131331': ('UnderVoltageCriticalHigh', 'CRITICAL', 'Voltage Event', 'Under-Voltage Warning (Lower critical, going high)'),
    '131332': ('UnderVoltageNonRecoverableLow', 'CRITICAL', 'Voltage Event', 'Under-Voltage Warning (Lower non-recoverable, going low)'),
    '131333': ('UnderVoltageNonRecoverableHigh', 'CRITICAL', 'Voltage Event', 'Under-Voltage Warning (Lower non-recoverable, going high)'),
    '131334': ('OverVoltageWarningLow', 'WARNING', 'Voltage Event', 'Over-Voltage Warning (Upper non-critical, going low)'),
    '131335': ('OverVoltageWarningHigh', 'WARNING', 'Voltage Event', 'Over-Voltage Warning (Upper non-critical, going high)'),
    '131336': ('OverVoltageCriticalLow', 'CRITICAL', 'Voltage Event', 'Over-Voltage Warning (Upper critical, going low)'),
    '131337': ('OverVoltageCriticalHigh', 'CRITICAL', 'Voltage Event', 'Over-Voltage Warning (Upper critical, going high)'),
    '131338': ('OverVoltageNonRecoverableLow', 'CRITICAL', 'Voltage Event', 'Over-Voltage Warning (Upper non-recoverable, going low)'),
    '131339': ('OverVoltageNonRecoverableHigh', 'CRITICAL', 'Voltage Event', 'Under-Voltage Warning (Upper non-recoverable, going high)'),
    '131456': ('UnderVoltageWarningLowCleared', 'INFORMATIONAL', 'Voltage Event', 'Under-Voltage Warning (Lower non-critical, going low) Cleared'),
    '131457': ('UnderVoltageWarningHighCleared', 'INFORMATIONAL', 'Voltage Event', 'Under-Voltage Warning (Lower non-critical, going high)Cleared'),
    '131458': ('UnderVoltageCriticalLowCleared', 'INFORMATIONAL', 'Voltage Event', 'Under-Voltage Warning (Lower critical, going low)Cleared'),
    '131459': ('UnderVoltageCriticalHighCleared', 'INFORMATIONAL', 'Voltage Event', 'Under-Voltage Warning (Lower critical, going high) Cleared'),
    '131460': ('UnderVoltageNonRecoverableLowCleared', 'INFORMATIONAL', 'Voltage Event', 'Under-Voltage Warning (Lower non-recoverable, going low)Cleared'),
    '131461': ('UnderVoltageNonRecoverableHighCleared', 'INFORMATIONAL', 'Voltage Event', 'Under-Voltage Warning (Lower non-recoverable, going high) Cleared'),
    '131462': ('OverVoltageWarningLowCleared', 'INFORMATIONAL', 'Voltage Event', 'Over-Voltage Warning (Upper non-critical, going low) Cleared'),
    '131463': ('OverVoltageWarningHighCleared', 'INFORMATIONAL', 'Voltage Event', 'Over-Voltage Warning (Upper non-critical, going high)Cleared'),
    '131464': ('OverVoltageCriticalLowCleared', 'INFORMATIONAL', 'Voltage Event', 'Over-Voltage Warning (Upper critical, going low) Cleared'),
    '131465': ('OverVoltageCriticalHighCleared', 'INFORMATIONAL', 'Voltage Event', 'Over-Voltage Warning (Upper critical, going high)Cleared'),
    '131466': ('OverVoltageNonRecoverableLowCleared', 'INFORMATIONAL', 'Voltage Event', 'Over-Voltage Warning (Upper non-recoverable, going low)Cleared'),
    '131467': ('OverVoltageNonRecoverableHighCleared', 'INFORMATIONAL', 'Voltage Event', 'Under-Voltage Warning (Upper non-recoverable, going high) Cleared'),
    '131840': ('GenericCriticalDiscreteVoltageCleared', 'INFORMATIONAL', 'Voltage Event', 'Generic Critical Voltage Problem Cleared'),
    '131841': ('GenericCriticalDiscreteVoltage', 'CRITICAL', 'Voltage Event', 'Generic Critical Voltage Problem (Transition to Critical from less severe)'),
    '132864': ('GenericCriticalDiscreteVoltage2Cleared', 'INFORMATIONAL', 'Voltage Event', 'Generic Critical Voltage Problem Cleared(Transition to OK)'),
    '132865': ('GenericNonCriticalDiscreteVoltage2', 'WARNING', 'Voltage Event', 'Generic Critical Voltage Problem (Transition to Non-critical from OK)'),
    '132866': ('GenericCriticalDiscreteVoltage2', 'CRITICAL', 'Voltage Event', 'Generic Critical Voltage Problem (Transition to Critical from less severe)'),
    '132867': ('GenericDiscreteVoltageWarning', 'WARNING', 'Voltage Event', 'Generic Voltage Warning (Transition to Non-Critical from less severe)'),
    '132868': ('GenericDiscreteVoltageWarning2', 'WARNING', 'Voltage Event', 'Generic Voltage Warning (Transition to Non-Critical from more severe)'),
    '132869': ('GenericDiscreteVoltageNonRecoverable', 'CRITICAL', 'Voltage Event', 'Generic Voltage Warning (Transition to Non-Recoverable)'),
    '132870': ('GenericDiscreteVoltageMonitor', 'INFORMATIONAL', 'Voltage Event', 'Generic Discrete Voltage (Monitor)'),
    '132871': ('GenericDiscreteVoltageInformational', 'INFORMATIONAL', 'Voltage Event', 'Generic Discrete Voltage (Informational)'),
    '196864': ('UnderCurrentWarningLow', 'WARNING', 'Current Event', 'Under-Current Warning (Lower non-critical, going low)'),
    '196865': ('UnderCurrentWarningHigh', 'WARNING', 'Current Event', 'Under-Current Warning (Lower non-critical, going high)'),
    '196866': ('UnderCurrentCriticalLow', 'CRITICAL', 'Current Event', 'Under-Current Warning (Lower critical, going low)'),
    '196867': ('UnderCurrentCriticalHigh', 'CRITICAL', 'Current Event', 'Under-Current Warning (Lower critical, going high)'),
    '196868': ('UnderCurrentNonRecoverableLow', 'CRITICAL', 'Current Event', 'Under-Current Warning (Lower non-recoverable, going low)'),
    '196869': ('UnderCurrentNonRecoverableHigh', 'CRITICAL', 'Current Event', 'Under-Current Warning (Lower non-recoverable, going high)'),
    '196870': ('OverCurrentWarningLow', 'WARNING', 'Current Event', 'Over-Current Warning (Upper non-critical, going low)'),
    '196871': ('OverCurrentWarningHigh', 'WARNING', 'Current Event', 'Over-Current Warning (Upper non-critical, going high)'),
    '196872': ('OverCurrentCriticalLow', 'CRITICAL', 'Current Event', 'Over-Current Warning (Upper critical, going low)'),
    '196873': ('OverCurrentCriticalHigh', 'CRITICAL', 'Current Event', 'Over-Current Warning (Upper critical, going high)'),
    '196874': ('OverCurrentNonRecoverableLow', 'CRITICAL', 'Current Event', 'Over-Current Warning (Upper non-recoverable, going low)'),
    '196875': ('OverCurrentNonRecoverableHigh', 'CRITICAL', 'Current Event', 'Under-Current Warning (Upper non-recoverable, going high)'),
    '196992': ('UnderCurrentWarningLowCleared', 'INFORMATIONAL', 'Current Event', 'Under-Current Warning (Lower non-critical, going low) Cleared'),
    '196993': ('UnderCurrentWarningHighCleared', 'INFORMATIONAL', 'Current Event', 'Under-Current Warning (Lower non-critical, going high)Cleared'),
    '196994': ('UnderCurrentCriticalLowCleared', 'INFORMATIONAL', 'Current Event', 'Under-Current Warning (Lower critical, going low)Cleared'),
    '196995': ('UnderCurrentCriticalHighCleared', 'INFORMATIONAL', 'Current Event', 'Under-Current Warning (Lower critical, going high) Cleared'),
    '196996': ('UnderCurrentNonRecoverableLowCleared', 'INFORMATIONAL', 'Current Event', 'Under-Current Warning (Lower non-recoverable, going low)Cleared'),
    '196997': ('UnderCurrentNonRecoverableHighCleared', 'INFORMATIONAL', 'Current Event', 'Under-Current Warning (Lower non-recoverable, going high) Cleared'),
    '196998': ('OverCurrentWarningLowCleared', 'INFORMATIONAL', 'Current Event', 'Over-Current Warning (Upper non-critical, going low) Cleared'),
    '196999': ('OverCurrentWarningHighCleared', 'INFORMATIONAL', 'Current Event', 'Over-Current Warning (Upper non-critical, going high)Cleared'),
    '197000': ('OverCurrentCriticalLowCleared', 'INFORMATIONAL', 'Current Event', 'Over-Current Warning (Upper critical, going low) Cleared'),
    '197001': ('OverCurrentCriticalHighCleared', 'INFORMATIONAL', 'Current Event', 'Over-Current Warning (Upper critical, going high)Cleared'),
    '197002': ('OverCurrentNonRecoverableLowCleared', 'INFORMATIONAL', 'Current Event', 'Over-Current Warning (Upper non-recoverable, going low)Cleared'),
    '197003': ('OverCurrentNonRecoverableHighCleared', 'INFORMATIONAL', 'Current Event', 'Under-Current Warning (Upper non-recoverable, going high) Cleared'),
    '262400': ('FanUnderSpeedWarningLow', 'WARNING', 'Fan Event', 'Fan Under Speed Warning (Lower non-critical, going low)'),
    '262401': ('FanUnderSpeedWarningHigh', 'WARNING', 'Fan Event', 'Fan Under Speed Warning (Lower non-critical, going high)'),
    '262402': ('FanUnderSpeedCriticalLow', 'CRITICAL', 'Fan Event', 'Fan Under Speed Warning (Lower critical, going low)'),
    '262403': ('FanUnderSpeedCriticalHigh', 'CRITICAL', 'Fan Event', 'Fan Under Speed Warning (Lower critical, going high)'),
    '262404': ('FanUnderSpeedNonRecoverableLow', 'CRITICAL', 'Fan Event', 'Fan Under Speed Warning (Lower non-recoverable, going low)'),
    '262405': ('FanUnderSpeedNonRecoverableHigh', 'CRITICAL', 'Fan Event', 'Fan Under Speed Warning (Lower non-recoverable, going high)'),
    '262406': ('FanOverSpeedWarningLow', 'WARNING', 'Fan Event', 'Fan Over Speed Warning (Upper non-critical, going low)'),
    '262407': ('FanOverSpeedWarningHigh', 'WARNING', 'Fan Event', 'Fan Over Speed Warning (Upper non-critical, going high)'),
    '262408': ('FanOverSpeedCriticalLow', 'CRITICAL', 'Fan Event', 'Fan Over Speed Warning (Upper critical, going low)'),
    '262409': ('FanOverSpeedCriticalHigh', 'CRITICAL', 'Fan Event', 'Fan Over Speed Warning (Upper critical, going high)'),
    '262410': ('FanOverSpeedNonRecoverableLow', 'CRITICAL', 'Fan Event', 'Fan Over Speed Warning (Upper non-recoverable, going low)'),
    '262411': ('FanOverSpeedNonRecoverableHigh', 'CRITICAL', 'Fan Event', 'Fan Under Speed Warning (Upper non-recoverable, going high)'),
    '262528': ('FanUnderSpeedWarningLowCleared', 'INFORMATIONAL', 'Fan Event', 'Fan Under Speed Warning (Lower non-critical, going low) Cleared'),
    '262529': ('FanUnderSpeedWarningHighCleared', 'INFORMATIONAL', 'Fan Event', 'Fan Under Speed Warning (Lower non-critical, going high)Cleared'),
    '262530': ('FanUnderSpeedCriticalLowCleared', 'INFORMATIONAL', 'Fan Event', 'Fan Under Speed Warning (Lower critical, going low)Cleared'),
    '262531': ('FanUnderSpeedCriticalHighCleared', 'INFORMATIONAL', 'Fan Event', 'Fan Under Speed Warning (Lower critical, going high) Cleared'),
    '262532': ('FanUnderSpeedNonRecoverableLowCleared', 'INFORMATIONAL', 'Fan Event', 'Fan Under Speed Warning (Lower non-recoverable, going low)Cleared'),
    '262533': ('FanUnderSpeedNonRecoverableHighCleared', 'INFORMATIONAL', 'Fan Event', 'Fan Under Speed Warning (Lower non-recoverable, going high) Cleared'),
    '262534': ('FanOverSpeedWarningLowCleared', 'INFORMATIONAL', 'Fan Event', 'Fan Over Speed Warning (Upper non-critical, going low) Cleared'),
    '262535': ('FanOverSpeedWarningHighCleared', 'INFORMATIONAL', 'Fan Event', 'Fan Over Speed Warning (Upper non-critical, going high)Cleared'),
    '262536': ('FanOverSpeedCriticalLowCleared', 'INFORMATIONAL', 'Fan Event', 'Fan Over Speed Warning (Upper critical, going low) Cleared'),
    '262537': ('FanOverSpeedCriticalHighCleared', 'INFORMATIONAL', 'Fan Event', 'Fan Over Speed Warning (Upper critical, going high)Cleared'),
    '262538': ('FanOverSpeedNonRecoverableLowCleared', 'INFORMATIONAL', 'Fan Event', 'Fan Over Speed Warning (Upper non-recoverable, going low)Cleared'),
    '262539': ('FanOverSpeedNonRecoverableHighCleared', 'INFORMATIONAL', 'Fan Event', 'Fan Under Speed Warning (Upper non-recoverable, going high) Cleared'),
    '264192': ('FanRemoved', 'CRITICAL', 'Fan Event', 'Fan Removed/Absent'),
    '264193': ('FanInserted', 'INFORMATIONAL', 'Fan Event', 'Fan Inserted/Present'),
    '264960': ('FanFullRedundancy', 'INFORMATIONAL', 'Fan Event', 'Fan redundancy has returned to Normal'),
    '264961': ('FanRedundancyLost', 'CRITICAL', 'Fan Event', 'Fan Redundancy has been Lost'),
    '264962': ('FanRedundancyDegraded', 'WARNING', 'Fan Event', 'Fan Redundancy is in a degraded state'),
    '356096': ('ChassisIntrusion', 'CRITICAL', 'Chassis Intrusion Event', 'Chassis Intrusion - Physical Security Violation'),
    '356097': ('ChassisDriveBayIntrusion', 'CRITICAL', 'Chassis Intrusion Event', 'Chassis Intrusion - Drive Bay Violation'),
    '356098': ('ChassisIOCardAreaIntrusion', 'CRITICAL', 'Chassis Intrusion Event', 'I/O Card Area Intrusion'),
    '356099': ('ChassisProcessorAreaIntrusion', 'CRITICAL', 'Chassis Intrusion Event', 'Processor Area Intrusion'),
    '356100': ('ChassisLANLeashLost', 'CRITICAL', 'Chassis Intrusion Event', 'LAN Leash Lost'),
    '356101': ('ChassisUnauthorizedDock', 'CRITICAL', 'Chassis Intrusion Event', 'Unauthorized dock'),
    '356102': ('ChassisFanAreaIntrusion', 'CRITICAL', 'Chassis Intrusion Event', 'Fan Area Intrusion'),
    '356224': ('ChassisIntrusionCleared', 'INFORMATIONAL', 'Chassis Intrusion Event', 'Chassis Intrusion( Physical Security Violation) Event Cleared'),
    '356225': ('ChassisDriveBayIntrusionCleared', 'INFORMATIONAL', 'Chassis Intrusion Event', 'Chassis Intrusion - Drive Bay Violation Cleared'),
    '356226': ('ChassisIOCardAreaIntrusionCleared', 'INFORMATIONAL', 'Chassis Intrusion Event', 'I/O Card Area Intrusion Cleared'),
    '356227': ('ChassisProcessorAreaIntrusionCleared', 'INFORMATIONAL', 'Chassis Intrusion Event', 'Processor Area Intrusion Cleared'),
    '356228': ('ChassisLANLeashLostCleared', 'INFORMATIONAL', 'Chassis Intrusion Event', 'LAN Leash Lost Cleared'),
    '356229': ('ChassisUnauthorizedDockCleared', 'INFORMATIONAL', 'Chassis Intrusion Event', 'Unauthorized dock Cleared'),
    '356230': ('ChassisFanAreaIntrusionCleared', 'INFORMATIONAL', 'Chassis Intrusion Event', 'Fan Area Intrusion Cleared'),
    '421632': ('SecureModeViolation', 'CRITICAL', 'Platform Securtiy Violation Attempt Event', 'Secure Mode Violation Attempt'),
    '421633': ('UserPasswordViolation', 'CRITICAL', 'Platform Securtiy Violation Attempt Event', 'User Password Violation Attempt'),
    '421634': ('SetupPasswordViolation', 'CRITICAL', 'Platform Securtiy Violation Attempt Event', 'Setup Password Violation Attempt'),
    '421635': ('NetworkBootPasswordViolation', 'CRITICAL', 'Platform Securtiy Violation Attempt Event', 'Network boot Password Violation Attempt'),
    '421636': ('OtherPasswordViolation', 'CRITICAL', 'Platform Securtiy Violation Attempt Event', 'Other pre-boot Password Violation Attempt'),
    '421637': ('OutOfBandAccessViolation', 'CRITICAL', 'Platform Securtiy Violation Attempt Event', 'Out-of-band access Violation Attempt'),
    '421760': ('SecureModeViolationCleared', 'INFORMATIONAL', 'Platform Securtiy Violation Attempt Event', 'Secure Mode Violation Attempt Cleared'),
    '421761': ('UserPasswordViolationCleared', 'INFORMATIONAL', 'Platform Securtiy Violation Attempt Event', 'User Password Violation Attempt Cleared'),
    '421762': ('SetupPasswordViolationCleared', 'INFORMATIONAL', 'Platform Securtiy Violation Attempt Event', 'Setup Password Violation Attempt Cleared'),
    '421763': ('NetworkBootPasswordViolationCleared', 'INFORMATIONAL', 'Platform Securtiy Violation Attempt Event', 'Network boot Password Violation Attempt Cleared'),
    '421764': ('OtherPasswordViolationCleared', 'INFORMATIONAL', 'Platform Securtiy Violation Attempt Event', 'Other pre-boot Password Violation Attempt Cleared'),
    '421765': ('OutOfBandAccessViolationCleared', 'INFORMATIONAL', 'Platform Securtiy Violation Attempt Event', 'Out-of-band access Violation Attempt Cleared'),
    '487168': ('ProcessorInternalError', 'CRITICAL', 'Processor Event', 'Processor Internal Error'),
    '487169': ('ProcessorThermalTrip', 'CRITICAL', 'Processor Event', 'Processor Thermal Trip (Over Temperature Shutdown)'),
    '487170': ('ProcessorBistError', 'CRITICAL', 'Processor Event', 'Processor Fault Resilient Booting (FRB) 1 / Processor BIST (Built In Self Test) Failure'),
    '487171': ('ProcessorFRB2Failure', 'CRITICAL', 'Processor Event', 'Processor Fault Resilient Booting (FRB) 2 / Hang in Power On Self Test (POST) Failure'),
    '487172': ('ProcessorFRB3Failure', 'CRITICAL', 'Processor Event', 'Processor Fault Resilient Booting (FRB) 3 / Processor Setup / Initialization Failure'),
    '487173': ('ProcessorConfigError', 'CRITICAL', 'Processor Event', 'Processor Configuration Error'),
    '487174': ('SMPIOSUncorrectableCPUComplexError', 'CRITICAL', 'Processor Event', 'SM BIOS Uncorrectable CPU-complex Error'),
    '487175': ('ProcessorPresenceDetected', 'INFORMATIONAL', 'Processor Event', 'Processor Presence Detected'),
    '487176': ('ProcessorDisabled', 'INFORMATIONAL', 'Processor Event', 'Processor Disabled'),
    '487177': ('TerminatorresenceDetected', 'INFORMATIONAL', 'Processor Event', 'Terminator Presence Detected'),
    '487178': ('ProcessorThrottle', 'WARNING', 'Processor Event', 'Processor Throttled (Processor Speed Reduced)'),
    '487296': ('ProcessorInternalErrorCleared', 'INFORMATIONAL', 'Processor Event', 'Processor Internal Error Cleared'),
    '487297': ('ProcessorThermalTripCleared', 'INFORMATIONAL', 'Processor Event', 'Processor Thermal Trip (Over Temperature Shutdown) Cleared'),
    '487298': ('ProcessorBistErrorCleared', 'INFORMATIONAL', 'Processor Event', 'Processor BIST (Built In Self Test) Failure Cleared'),
    '487299': ('ProcessorFRB2FailureCleared', 'INFORMATIONAL', 'Processor Event', 'Processor Fault Resilient Booting (FRB) 2 / Hang in Power On Self Test (POST) Failure Cleared'),
    '487300': ('ProcessorFRB3FailureCleared', 'INFORMATIONAL', 'Processor Event', 'Processor Fault Resilient Booting (FRB) 3 / Processor Setup / Initialization Failure Cleared'),
    '487301': ('ProcessorConfigErrorCleared', 'INFORMATIONAL', 'Processor Event', 'Processor Configuration Error Cleared'),
    '487302': ('ProcessorConfigErrorCleared', 'CRITICAL', 'Processor Event', 'Processor Configuration Error Cleared'),
    '487303': ('SMPIOSUncorrectableCPUComplexErrorCleared', 'CRITICAL', 'Processor Event', 'SM BIOS Uncorrectable CPU-complex Error Cleared'),
    '487306': ('ProcessorThrottleCleared', 'INFORMATIONAL', 'Processor Event', 'Processor Throttle Cleared (Normal Processor Speed)'),
    '487308': ('CorrectableMachineCheckErrorCleared', 'INFORMATIONAL', 'Processor Event', 'Correctable Machine Check Error Cleared'),
    '525056': ('PowerSupplyStateDeasserted', 'CRITICAL', 'Power Supply Event', 'Power Supply is disconnected from AC Power.'),
    '525057': ('PowerSupplyStateAsserted', 'INFORMATIONAL', 'Power Supply Event', 'Power Supply is connected to AC Power.'),
    '525313': ('PowerSupplyPredictiveFailureAsserted', 'CRITICAL', 'Power Supply Event', 'Power Supply Predictive Failure Deasserted'),
    '525312': ('PowerSupplyPredictiveFailureDeasserted', 'INFORMATIONAL', 'Power Supply Event', 'Power Supply Predictive Failure Asserted'),
    '527104': ('PowerSupplyFullRedundancy', 'INFORMATIONAL', 'Power Supply Event', 'Power Supply Redundancy Has Returned to Normal'),
    '527105': ('PowerSupplyRedundancyLost', 'CRITICAL', 'Power Supply Event', 'Power Supply Redundancy has been Lost'),
    '527106': ('PowerSupplyRedundancyDegraded', 'WARNING', 'Power Supply Event', 'Power Supply Redundancy is in a degraded state'),
    '552704': ('PowerSupplyPresenceDeteced', 'INFORMATIONAL', 'Power Supply Event', 'Power Supply Inserted'),
    '552705': ('PowerSupplyFailureDetected', 'CRITICAL', 'Power Supply Event', 'Power Supply failure detected'),
    '552706': ('PowerSupplyWarning', 'WARNING', 'Power Supply Event', 'Power Supply Warning'),
    '552707': ('PowerSupplyACLost', 'CRITICAL', 'Power Supply Event', 'Power Supply AC Lost'),
    '552708': ('PowerSupplyInputLost', 'CRITICAL', 'Power Supply Event', 'Power Supply input lost or out-of-range'),
    '552709': ('PowerSupplyInputOutOfRange', 'CRITICAL', 'Power Supply Event', 'Power Supply input out-of-range, but present'),
    '552710': ('PowerSupplyConfigError', 'CRITICAL', 'Power Supply Event', 'Power Supply Configuration error'),
    '552832': ('PowerSupplyPresenceRemoved', 'WARNING', 'Power Supply Event', 'Power Supply Removed'),
    '552833': ('PowerSupplyFailureCleared', 'INFORMATIONAL', 'Power Supply Event', 'Power Supply Failure Cleared'),
    '552834': ('PowerSupplyWarningCleared', 'INFORMATIONAL', 'Power Supply Event', 'Power Supply Warning Cleared'),
    '552835': ('PowerSupplyACBack', 'INFORMATIONAL', 'Power Supply Event', 'Power Supply AC Restored'),
    '552836': ('PowerSupplyInputBack', 'INFORMATIONAL', 'Power Supply Event', 'Power Supply input lost or out-of-range Restored'),
    '552837': ('PowerSupplyInputOutOfRange', 'INFORMATIONAL', 'Power Supply Event', 'Power Supply input out-of-range restored'),
    '552838': ('PowerSupplyConfigErrorCleared', 'CRITICAL', 'Power Supply Event', 'Power Supply Configuration error Cleared'),
    '590592': ('PowerUnitStateDeasserted', 'CRITICAL', 'Power Unit Event', 'Run-time power fault has occurred.'),
    '590593': ('PowerUnitStateAsserted', 'INFORMATIONAL', 'Power Unit Event', 'Host power-on sequence has been completed successfully.'),
    '592640': ('PowerUnitRedundancyOk', 'INFORMATIONAL', 'Power Unit Event', 'Power Unit Redundancy has been restored'),
    '592641': ('PowerUnitRedundancyLost', 'CRITICAL', 'Power Unit Event', 'Power Unit Redundancy has been Lost'),
    '618240': ('PowerUnitPowerOff', 'INFORMATIONAL', 'Power unit event', 'Power unit is off.'),
    '618241': ('PowerUnitPowerCycle', 'INFORMATIONAL', 'Power unit event', 'Power unit is power cycled'),
    '618242': ('PowerUnit240VAPowerDown', 'INFORMATIONAL', 'Power unit event', 'Power unit 240VA Power Down'),
    '618243': ('PowerUnitInterlockPowerDown', 'INFORMATIONAL', 'Power unit event', 'Power unit Interlock Power Down'),
    '618244': ('PowerUnitACLost', 'INFORMATIONAL', 'Power unit event', 'Power unit AC lost / Power input lost'),
    '618245': ('PowerUnitSoftPowerControlFail', 'INFORMATIONAL', 'Power unit event', 'Soft Power Control Failure'),
    '618246': ('PowerUnitFailure', 'INFORMATIONAL', 'Power unit event', 'Power Unit Failure detected'),
    '618247': ('PowerUnitPredictiveFailure', 'INFORMATIONAL', 'Power unit event', 'Power Unit Predictive Failure'),
    '618368': ('PowerUnitPowerOn', 'INFORMATIONAL', 'Power Unit event', 'Power Unit is on.'),
    '618369': ('PowerUnitPowerCycleCompleted', 'INFORMATIONAL', 'Power unit event', 'Power unit - Power Cycle Completed'),
    '618370': ('PowerUnit240VAPowerUp', 'INFORMATIONAL', 'Power unit event', 'Power unit 240VA Power Up'),
    '618371': ('PowerUnitInterlockPowerUp', 'INFORMATIONAL', 'Power unit event', 'Power unit Interlock Power Up'),
    '618372': ('PowerUnitACRestored', 'INFORMATIONAL', 'Power unit event', 'Power unit AC/Power input restored'),
    '618373': ('PowerUnitSoftPowerControlFailCleared', 'INFORMATIONAL', 'Power unit event', 'Soft Power Control Failure Cleared'),
    '618374': ('PowerUnitFailureCleared', 'INFORMATIONAL', 'Power unit event', 'Power Unit Failure Cleared'),
    '618375': ('PowerUnitPredictiveFailureCleared', 'INFORMATIONAL', 'Power unit event', 'Power Unit Predictive Failure Cleared'),
    '655616': ('CoolingDeviceUnderSpeedWarningLow', 'WARNING', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Lower non-critical, going low)'),
    '655617': ('CoolingDeviceUnderSpeedWarningHigh', 'WARNING', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Lower non-critical, going high)'),
    '655618': ('CoolingDeviceUnderSpeedCriticalLow', 'CRITICAL', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Lower critical, going low)'),
    '655619': ('CoolingDeviceUnderSpeedCriticalHigh', 'CRITICAL', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Lower critical, going high)'),
    '655620': ('CoolingDeviceUnderSpeedNonRecoverableLow', 'CRITICAL', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Lower non-recoverable, going low)'),
    '655621': ('CoolingDeviceUnderSpeedNonRecoverableHigh', 'CRITICAL', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Lower non-recoverable, going high)'),
    '655622': ('CoolingDeviceOverSpeedWarningLow', 'WARNING', 'Cooling Device Event', 'Cooling Device Over Speed Warning (Upper non-critical, going low)'),
    '655623': ('CoolingDeviceOverSpeedWarningHigh', 'WARNING', 'Cooling Device Event', 'Cooling Device Over Speed Warning (Upper non-critical, going high)'),
    '655624': ('CoolingDeviceOverSpeedCriticalLow', 'CRITICAL', 'Cooling Device Event', 'Cooling Device Over Speed Warning (Upper critical, going low)'),
    '655625': ('CoolingDeviceOverSpeedCriticalHigh', 'CRITICAL', 'Cooling Device Event', 'Cooling Device Over Speed Warning (Upper critical, going high)'),
    '655626': ('CoolingDeviceOverSpeedNonRecoverableLow', 'CRITICAL', 'Cooling Device Event', 'Cooling Device Over Speed Warning (Upper non-recoverable, going low)'),
    '655627': ('CoolingDeviceOverSpeedNonRecoverableHigh', 'CRITICAL', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Upper non-recoverable, going high)'),
    '655744': ('CoolingDeviceUnderSpeedWarningLowCleared', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Lower non-critical, going low) Cleared'),
    '655745': ('CoolingDeviceUnderSpeedWarningHighCleared', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Lower non-critical, going high)Cleared'),
    '655746': ('CoolingDeviceUnderSpeedCriticalLowCleared', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Lower critical, going low)Cleared'),
    '655747': ('CoolingDeviceUnderSpeedCriticalHighCleared', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Lower critical, going high) Cleared'),
    '655748': ('CoolingDeviceUnderSpeedNonRecoverableLowCleared', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Lower non-recoverable, going low)Cleared'),
    '655749': ('CoolingDeviceUnderSpeedNonRecoverableHighCleared', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Lower non-recoverable, going high) Cleared'),
    '655750': ('CoolingDeviceOverSpeedWarningLowCleared', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Over Speed Warning (Upper non-critical, going low) Cleared'),
    '655751': ('CoolingDeviceOverSpeedWarningHighCleared', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Over Speed Warning (Upper non-critical, going high)Cleared'),
    '655752': ('CoolingDeviceOverSpeedCriticalLowCleared', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Over Speed Warning (Upper critical, going low) Cleared'),
    '655753': ('CoolingDeviceOverSpeedCriticalHighCleared', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Over Speed Warning (Upper critical, going high)Cleared'),
    '655754': ('CoolingDeviceOverSpeedNonRecoverableLowCleared', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Over Speed Warning (Upper non-recoverable, going low)Cleared'),
    '655755': ('CoolingDeviceOverSpeedNonRecoverableHighCleared', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Under Speed Warning (Upper non-recoverable, going high) Cleared'),
    '657408': ('CoolingDeviceRemoved', 'CRITICAL', 'Cooling Device Event', 'Cooling Device Removed/Absent'),
    '657409': ('CoolingDeviceInserted', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device Inserted/Present'),
    '658176': ('CoolingDeviceFullRedundancy', 'INFORMATIONAL', 'Cooling Device Event', 'Cooling Device redundancy has returned to Normal'),
    '658177': ('CoolingDeviceRedundancyLost', 'CRITICAL', 'Cooling Device Event', 'Cooling Device Redundancy has been Lost'),
    '658178': ('CoolingDeviceRedundancyDegraded', 'WARNING', 'Cooling Device Event', 'Cooling Device Redundancy is in a degraded state'),
    '787456': ('MemoryPredictiveFailureDeasserted', 'INFORMATIONAL', 'Memory Event', 'Memory Predictive Failure state has been cleared.'),
    '787457': ('MemoryPredictiveFailureAsserted', 'CRITICAL', 'Memory Event', 'Memory Predictive Failure has been asserted.'),
    '814848': ('MemoryCorrectableEccError', 'INFORMATIONAL', 'Memory Event', 'Correctable ECC or other correctable memory error detected.'),
    '814849': ('MemoryUncorrectableEccError', 'INFORMATIONAL', 'Memory Event', 'Uncorrectable ECC or other uncorrectable memory error detected.'),
    '814850': ('MemoryParityError', 'INFORMATIONAL', 'Memory Event', 'Parity error detected.'),
    '814851': ('MemoryScrubFailed', 'INFORMATIONAL', 'Memory Event', 'Memory Scrub Failed'),
    '814852': ('MemoryDeviceDisabled', 'INFORMATIONAL', 'Memory Event', 'Memory Device Disabled.'),
    '814853': ('MemoryCorrectableECC', 'INFORMATIONAL', 'Memory Event', 'Correctable ECC / other correctable memory error logging limit reached'),
    '814854': ('MemoryPresenceDetectedAssert', 'INFORMATIONAL', 'Memory Event', 'Memory Presence detected.'),
    '814855': ('MemoryConfigurationError', 'INFORMATIONAL', 'Memory Event', 'Memory Configuration Error  detected.'),
    '814856': ('MemorySpareUnit', 'INFORMATIONAL', 'Memory Event', 'Spare Unit of Memory detected'),
    '814857': ('MemoryAutomaticallyThrottled', 'INFORMATIONAL', 'Memory Event', 'Memory Automatically Throttled'),
    '814858': ('MemoryCriticalOvertemperature', 'INFORMATIONAL', 'Memory Event', 'Memory event - Critical Overtemperature'),
    '814976': ('MemoryCorrectableEccErrorCleared', 'INFORMATIONAL', 'Memory Event', 'Correctable ECC or other correctable memory error cleared.'),
    '814977': ('MemoryUncorrectableEccErrorCleared', 'INFORMATIONAL', 'Memory Event', 'Uncorrectable ECC or other uncorrectable memory error Cleared.'),
    '814978': ('MemoryParityErrorCleared', 'INFORMATIONAL', 'Memory Event', 'Parity error Cleared.'),
    '814979': ('MemoryScrubFailureCleared', 'INFORMATIONAL', 'Memory Event', 'Memory Scrub Failure Cleared'),
    '814980': ('MemoryDeviceEnabled', 'INFORMATIONAL', 'Memory Event', 'Memory Device Enabled.'),
    '814981': ('MemoryCorrectableECCCleared', 'INFORMATIONAL', 'Memory Event', 'Correctable ECC / other correctable memory error logging limit reached Cleared'),
    '814982': ('MemoryPresenceNotDetected', 'INFORMATIONAL', 'Memory Event', 'Memory Presence not detected'),
    '814983': ('MemoryConfigurationErrorCleared', 'INFORMATIONAL', 'Memory Event', 'Memory Configuration Error  Cleared.'),
    '814984': ('MemorySpareUnitDeassert', 'INFORMATIONAL', 'Memory Event', 'Spare Unit of Memory detected Deassert'),
    '814985': ('MemoryAutomaticallyThrottledCleared', 'INFORMATIONAL', 'Memory Event', 'Memory Automatically Throttled Cleared'),
    '814986': ('MemoryCriticalOvertemperatureCleared', 'INFORMATIONAL', 'Memory Event', 'Memory event - Critical Overtemperature Cleared'),
    '852992': ('DriveSlotPredictiveFailureDeasserted', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive Fault LED is OFF.'),
    '852993': ('DriveSlotPredictiveFailureAsserted', 'MAJOR', 'Drive Slot Event', 'Hard Disk Drive Fault LED is ON.'),
    '880384': ('DriveSlotDriveRemovedOrAbsent', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive is absent or has been removed.'),
    '880385': ('DriveSlotDriveFault', 'CRITICAL', 'Drive Slot Event', 'Hard Disk Drive Fault'),
    '880386': ('DriveSlotPredictiveFailure', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive Predictive Failure'),
    '880387': ('DriveSlotHotSpare', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive Hot spare (Ready to Remove) '),
    '880388': ('DriveSlotConsistencyCheckInProgress', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive Consistency Check / Parity Check in progress'),
    '880389': ('DriveSlotInCriticalArray', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive In Critical Array'),
    '880390': ('DriveSlotInFailedArray', 'CRITICAL', 'Drive Slot Event', 'Hard Disk Drive In Failed Array'),
    '880391': ('DriveSlotRebuildOrRemapInProgress', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive Rebuild/Remap in progress'),
    '880392': ('DriveSlotRebuildOrRemapAborted', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive Rebuild/Remap Aborted'),
    '880512': ('DriveSlotDriveInsertedOrPresent', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive is present or has been inserted.'),
    '880513': ('DriveSlotDriveFaultCleared', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive Fault Cleared'),
    '880514': ('DriveSlotPredictiveFailureCleared', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive Predictive Failure Cleared'),
    '880515': ('DriveSlotHotSpareDeasserted', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive Hot spare'),
    '880516': ('DriveSlotConsistencyCheckInProgressDeasserted', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive Consistency Check / Parity Check in progress Deasserted'),
    '880517': ('DriveSlotInCriticalArrayDeasserted', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive In Critical Array Deasserted'),
    '880518': ('DriveSlotInFailedArrayDeasserted', 'CRITICAL', 'Drive Slot Event', 'Hard Disk Drive In Failed Array Deasserted'),
    '880519': ('DriveSlotRebuildOrRemapInProgressDeasserted', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive Rebuild/Remap in progress Deasserted(completed)'),
    '880520': ('DriveSlotRebuildOrRemapAbortedDeasserted', 'INFORMATIONAL', 'Drive Slot Event', 'Hard Disk Drive Rebuild/Remap Aborted Deasserted(completed)'),
    '918528': ('POSTMemoryResizeFailureDeasserted', 'INFORMATIONAL', 'POST Memory Resize Event', 'POST Memory Resize Failure Deasserted'),
    '918529': ('POSTMemoryResizeFailureAsserted', 'MAJOR', 'POST Memory Resize Event', 'POST Memory Resize Failure Asserted'),
    '1011456': ('BIOSPOSTCodeError', 'CRITICAL', 'System Firmware Progress Event', 'System Firmware Progress: BIOS POST code error'),
    '1011457': ('SystemFirmwareHang', 'CRITICAL', 'System Firmware Progress Event', 'System Firmware Hang'),
    '1011458': ('SystemFirmwareProgress', 'INFORMATIONAL', 'System Firmware Progress Event', 'System Firmware Progress'),
    '1011584': ('BIOSPOSTCodeErrorCleared', 'INFORMATIONAL', 'System Firmware Progress Event', 'System Firmware Progress: BIOS POST code error Cleared'),
    '1011585': ('SystemFirmwareHangCleared', 'INFORMATIONAL', 'System Firmware Progress Event', 'System Firmware Hang Cleared'),
    '1011586': ('SystemFirmwareProgressCompleted', 'INFORMATIONAL', 'System Firmware Progress Event', 'System Firmware Progress Completed '),
    '1076992': ('CorrectableMemoryErrorLoggingDisabled', 'INFORMATIONAL', 'System Event Log', 'Correctable Memory Error Logging Disabled'),
    '1076993': ('EventTypeLoggingDisabled', 'INFORMATIONAL', 'System Event Log', 'Event Type Logging Disabled.'),
    '1076994': ('SELAreaResetOrCleared', 'INFORMATIONAL', 'System Event Log', 'SEL Area Reset/Cleared'),
    '1076995': ('EventLoggingDisabled', 'CRITICAL', 'System Event Log', 'System Event Logging Disabled'),
    '1076996': ('SelFull', 'INFORMATIONAL', 'System Event Log', 'SEL Full.'),
    '1076997': ('SelAlmostFull', 'INFORMATIONAL', 'System Event Log', 'SEL Almost Full.'),
    '1076998': ('CorrectableMachineCheckErrorLoggingDisabled', 'INFORMATIONAL', 'System Event Log', 'Correctable Machine Check Error Logging Disabled'),
    '1077120': ('CorrectableMemoryErrorLoggingEnabled', 'INFORMATIONAL', 'System Event Log', 'Correctable Memory Error Logging Enabled'),
    '1077121': ('EventTypeLoggingEnabled', 'INFORMATIONAL', 'System Event Log', 'Event Type Logging Enabled.'),
    '1077122': ('SELAreaResetOrClearedEventDeassert', 'INFORMATIONAL', 'System Event Log', 'SEL Area Reset/Cleared Event Deasserted'),
    '1077123': ('EventLoggingDisabled', 'INFORMATIONAL', 'System Event Log', 'System Event Logging Enabled'),
    '1077124': ('SelFullEventCleared', 'INFORMATIONAL', 'System Event Log', 'SEL Full Event Cleared'),
    '1077125': ('SelAlmostFullEventCleared', 'INFORMATIONAL', 'System Event Log', 'SEL Almost Full Event Cleared'),
    '1077126': ('CorrectableMachineCheckErrorLoggingEnabled', 'INFORMATIONAL', 'System Event Log', 'Correctable Machine Check Error Logging Enabled'),
    '1142528': ('BIOSWatchdogReset', 'INFORMATIONAL', 'Watchdog Event', 'BIOS Watchdog Reset'),
    '1142529': ('OSWatchdogReset', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog Reset'),
    '1142530': ('OSWatchdogShutDown', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog Shut Down'),
    '1142531': ('OSWatchdogPowerDown', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog Power Down'),
    '1142532': ('OSWatchdogPowerCycle', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog Power Cycle'),
    '1142533': ('OSWatchdogNMIOrDiagnosticInterrupt', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog NMI / Diagnostic Interrupt'),
    '1142534': ('OSWatchdogExpired', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog Expired, status only'),
    '1142535': ('OSWatchdogPreTimeoutInterrupt', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog pre-timeout Interrupt, non-NMI'),
    '1142656': ('BIOSWatchdogResetDeasserted', 'INFORMATIONAL', 'Watchdog Event', 'BIOS Watchdog Reset Deasserted'),
    '1142657': ('OSWatchdogResetDeasserted', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog Reset Deasserted'),
    '1142658': ('OSWatchdogShutDownDeasserted', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog Shut Down Deasserted'),
    '1142659': ('OSWatchdogPowerDownDeasserted', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog Power Down Deasserted'),
    '1142660': ('OSWatchdogPowerCycleDeasserted', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog Power Cycle Deasserted'),
    '1142661': ('OSWatchdogNMIOrDiagnosticInterruptCleared', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog NMI / Diagnostic Interrupt Cleared'),
    '1142662': ('OSWatchdogExpiredEventCleared', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog Expired, status only Event Cleared'),
    '1142663': ('OSWatchdogPreTimeoutInterruptCleared', 'INFORMATIONAL', 'Watchdog Event', 'OS Watchdog pre-timeout Interrupt Cleared'),
    '1208064': ('SystemReconfigured', 'INFORMATIONAL', 'System Event', 'System Reconfigured'),
    '1208065': ('OEMSystemBootEvent', 'WARNING', 'System Event', 'OEM System Boot Event'),
    '1208066': ('UndeterminedSystemHardwareFailure', 'CRITICAL', 'System Event', 'Undetermined system hardware failure'),
    '1208067': ('EntryAddedToAuxiliaryLog', 'INFORMATIONAL', 'System Event', 'SEL Entry added to Auxiliary Log'),
    '1208068': ('PEFAction', 'INFORMATIONAL', 'System Event', 'PEF Action is about to be taken. Event filters have been matched.'),
    '1208069': ('TimestampClockSynch', 'INFORMATIONAL', 'System Event', 'Timestamp Clock Synch'),
    '1208192': ('SystemReconfiguredDeassert', 'INFORMATIONAL', 'System Event', 'System Reconfigured Event Cleared'),
    '1208193': ('OEMSystemBootEventCleared', 'INFORMATIONAL', 'System Event', 'OEM System Boot Event Cleared'),
    '1208194': ('UndeterminedSystemHardwareFailureCleared', 'CRITICAL', 'System Event', 'Undetermined system hardware failure Cleared'),
    '1208195': ('EntryAddedToAuxiliaryLogDeassert', 'INFORMATIONAL', 'System Event', 'SEL Entry added to Auxiliary Log Deasserted'),
    '1208196': ('PEFActionEventDeassert', 'INFORMATIONAL', 'System Event', 'PEF Action Event Deasserted'),
    '1208197': ('TimestampClockSynchEventDeassert', 'INFORMATIONAL', 'System Event', 'Timestamp Clock Synch Event Deasserted'),
    '1273600': ('CriticalInterruptFrontPanelNMI', 'CRITICAL', 'Critical Interrupts Event', 'Front Panel NMI / Diagnostic Interrupt'),
    '1273601': ('CriticalInterruptBusTimeout', 'CRITICAL', 'Critical Interrupts Event', 'Critical Interrupt, Bus Timeout error'),
    '1273602': ('CriticalInterruptIOChannelNMI', 'CRITICAL', 'Critical Interrupts Event', 'Critical Interrupt, IO Channel check NMI error'),
    '1273603': ('CriticalInterruptSoftwareNMI', 'CRITICAL', 'Critical Interrupts Event', 'Critical Interrupt, software NMI error'),
    '1273604': ('CriticalInterruptPCIPERR', 'CRITICAL', 'Critical Interrupts Event', 'Critical Interrupt, PCI PERR parity error'),
    '1273605': ('CriticalInterruptPCISERR', 'CRITICAL', 'Critical Interrupts Event', 'Critical Interrupt, PCI SERR parity error'),
    '1273606': ('CriticalInterruptEISAFailSafeTimeout', 'CRITICAL', 'Critical Interrupts Event', 'Critical Interrupt, EISA Fail Safe Timeout'),
    '1273607': ('CriticalInterruptBusCorrectableError', 'CRITICAL', 'Critical Interrupts Event', 'Critical Interrupt, Bus Correctable Error'),
    '1273608': ('CriticalInterruptBusUncorrect', 'CRITICAL', 'Critical Interrupts Event', 'Critical Interrupt, Bus Uncorrectable error'),
    '1273609': ('CriticalInterruptFatalNMI', 'CRITICAL', 'Critical Interrupts Event', 'Critical Interrupt, Fatal NMI error'),
    '1273610': ('CriticalInterruptFatalBusError', 'CRITICAL', 'Critical Interrupts Event', 'Critical Interrupt, Bus Fatal Error'),
    '1273611': ('CriticalInterruptBusDegraded', 'CRITICAL', 'Critical Interrupts Event', 'Critical Interrupt, Bus Degraded (bus operating in a degraded performance state)'),
    '1273728': ('CriticalInterruptFrontPanelNMICleared', 'INFORMATIONAL', 'Critical Interrupts Event', 'Front Panel NMI / Diagnostic Interrupt Cleared'),
    '1273729': ('CriticalInterruptBusTimeoutCleared', 'INFORMATIONAL', 'Critical Interrupts Event', 'Critical Interrupt, Bus Timeout error Cleared'),
    '1273730': ('CriticalInterruptIOChannelNMICleared', 'INFORMATIONAL', 'Critical Interrupts Event', 'Critical Interrupt, IO Channel check NMI error Cleared'),
    '1273731': ('CriticalInterruptSoftwareNMICleared', 'INFORMATIONAL', 'Critical Interrupts Event', 'Critical Interrupt, software NMI error Cleared'),
    '1273732': ('CriticalInterruptPCIPERRCleared', 'INFORMATIONAL', 'Critical Interrupts Event', 'Critical Interrupt, PCI PERR parity error Cleared'),
    '1273733': ('CriticalInterruptPCISERRCleared', 'INFORMATIONAL', 'Critical Interrupts Event', 'Critical Interrupt, PCI SERR parity error Cleared'),
    '1273734': ('CriticalInterruptEISAFailSafeTimeoutCleared', 'INFORMATIONAL', 'Critical Interrupts Event', 'Critical Interrupt, EISA Fail Safe Timeout Event Cleared'),
    '1273735': ('CriticalInterruptBusCorrectableErrorCleared', 'INFORMATIONAL', 'Critical Interrupts Event', 'Critical Interrupt, Bus Correctable Error Cleared'),
    '1273736': ('CriticalInterruptBusUncorrectCleared', 'INFORMATIONAL', 'Critical Interrupts Event', 'Critical Interrupt, Bus Uncorrectable error Cleared'),
    '1273737': ('CriticalInterruptFatalNMICleared', 'INFORMATIONAL', 'Critical Interrupts Event', 'Critical Interrupt, Fatal NMI error Cleared'),
    '1273738': ('CriticalInterruptFatalBusErrorCleared', 'INFORMATIONAL', 'Critical Interrupts Event', 'Critical Interrupt, Bus Fatal Error Cleared'),
    '1273739': ('CriticalInterruptBusDegradedEventCleared', 'INFORMATIONAL', 'Critical Interrupts Event', 'Critical Interrupt, Bus Degraded (bus operating in a degraded performance state) Event Cleared'),
    '1339136': ('PowerButtonPressed', 'INFORMATIONAL', 'Button/Switch Event', 'Power Button pressed.'),
    '1339137': ('SleepButtonPressed', 'INFORMATIONAL', 'Button/Switch Event', 'Sleep Button pressed.'),
    '1339138': ('ResetButtonPressed', 'INFORMATIONAL', 'Button/Switch Event', 'Reset Button pressed.'),
    '1339139': ('FRULatchOpen', 'INFORMATIONAL', 'Button/Switch Event', 'FRU latch open'),
    '1339140': ('FRUServiceRequestButton', 'INFORMATIONAL', 'Button/Switch Event', 'FRU service request button'),
    '1339264': ('PowerButtonReleased', 'INFORMATIONAL', 'Button/Switch Event', 'Power Button Released.'),
    '1339265': ('SleepButtonReleased', 'INFORMATIONAL', 'Button/Switch Event', 'Sleep Button Released.'),
    '1339266': ('ResetButtonReleased', 'INFORMATIONAL', 'Button/Switch Event', 'Reset Button Released.'),
    '1339267': ('FRULatchClosed', 'INFORMATIONAL', 'Button/Switch Event', 'FRU latch Closed'),
    '1339268': ('FRUServiceRequestButtonReleased', 'INFORMATIONAL', 'Button/Switch Event', 'FRU service request button Released'),
    '1377024': ('BoardStateDeasserted', 'INFORMATIONAL', 'Module/Board Event', 'Module/Board State Deasserted'),
    '1377025': ('BoardStateAsserted', 'INFORMATIONAL', 'Module/Board Event', 'Module/Board State Asserted'),
    '1377280': ('BoardPredictiveFailureDeasserted', 'INFORMATIONAL', 'Module/Board Event', 'Module/Board Predictive Failure Deasserted'),
    '1377281': ('BoardPredictiveFailureAsserted', 'INFORMATIONAL', 'Module/Board Event', 'Module/Board Predictive Failure Asserted'),
    '1442560': ('MicrocontrollerStateDeasserted', 'INFORMATIONAL', 'Microcontroller/Coprocessor Event', 'Microcontroller/Coprocessor State Deasserted'),
    '1442561': ('MicrocontrollerStateAsserted', 'INFORMATIONAL', 'Microcontroller/Coprocessor Event', 'Microcontroller/Coprocessor State Asserted'),
    '1442816': ('MicrocontrollerPredictiveFailureDeasserted', 'INFORMATIONAL', 'Microcontroller/Coprocessor Event', 'Microcontroller/Coprocessor Predictive Failure Deasserted'),
    '1442817': ('MicrocontrollerPredictiveFailureAsserted', 'INFORMATIONAL', 'Microcontroller/Coprocessor Event', 'Microcontroller/Coprocessor Predictive Failure Asserted'),
    '1508096': ('AddInCardStateDeasserted', 'INFORMATIONAL', 'Add-in Card Event', 'Add-in Card State Deasserted'),
    '1508097': ('AddInCardStateAsserted', 'INFORMATIONAL', 'Add-in Card Event', 'Add-in Card State Asserted'),
    '1508352': ('AddInCardPredictiveFailureDeasserted', 'INFORMATIONAL', 'Add-in Card Event', 'Add-in Card Predictive Failure Deasserted'),
    '1508353': ('AddInCardPredictiveFailureAsserted', 'INFORMATIONAL', 'Add-in Card Event', 'Add-in Card Predictive Failure Asserted'),
    '1573632': ('ChassisStateDeasserted', 'INFORMATIONAL', 'Chassis Event', 'Chassis State Deasserted'),
    '1573633': ('ChassisStateAsserted', 'INFORMATIONAL', 'Chassis Event', 'Chassis State Asserted'),
    '1573888': ('ChassisPredictiveFailureDeasserted', 'INFORMATIONAL', 'Chassis Event', 'Chassis Predictive Failure Deasserted'),
    '1573889': ('ChassisPredictiveFailureAsserted', 'INFORMATIONAL', 'Chassis Event', 'Chassis Predictive Failure Asserted'),
    '1639168': ('ChipSetStateDeasserted', 'INFORMATIONAL', 'Chip Set Event', 'Chip Set State Deasserted'),
    '1639169': ('ChipSetStateAsserted', 'INFORMATIONAL', 'Chip Set Event', 'Chip Set State Asserted'),
    '1639424': ('ChipSetPredictiveFailureDeasserted', 'INFORMATIONAL', 'Chip Set Event', 'Chip Set Predictive Failure Deasserted'),
    '1639425': ('ChipSetPredictiveFailureAsserted', 'INFORMATIONAL', 'Chip Set Event', 'Chip Set Predictive Failure Asserted'),
    '1666816': ('SoftPowerControlFailure', 'WARNING', 'Chip Set Event', 'Soft Power Control Failure'),
    '1666817': ('ThermalTrip', 'WARNING', 'Chip Set Event', 'Thermal Trip Occured'),
    '1666944': ('SoftPowerControlFailureCleared', 'INFORMATIONAL', 'Chip Set Event', 'Soft Power Control Failure Cleared'),
    '1666945': ('ThermalTripCleared', 'INFORMATIONAL', 'Chip Set Event', 'Thermal Trip Cleared'),
    '1704704': ('FRUStateDeasserted', 'INFORMATIONAL', 'Other FRU Event', 'FRU State Deasserted'),
    '1704705': ('FRUStateAsserted', 'INFORMATIONAL', 'Other FRU Event', 'FRU State Asserted'),
    '1704960': ('FRUPredictiveFailureDeasserted', 'INFORMATIONAL', 'Other FRU Event', 'FRU Predictive Failure Deasserted'),
    '1704961': ('FRUPredictiveFailureAsserted', 'INFORMATIONAL', 'Other FRU Event', 'FRU Predictive Failure Asserted'),
    '1770240': ('CableStateDeasserted', 'INFORMATIONAL', 'Other Cable / Interconnect Event', 'Cable / Interconnect State Deasserted'),
    '1770241': ('CableStateAsserted', 'INFORMATIONAL', 'Other Cable / Interconnect Event', 'Cable / Interconnect State Asserted'),
    '1770496': ('CablePredictiveFailureDeasserted', 'INFORMATIONAL', 'Other Cable / Interconnect Event', 'Cable / Interconnect Predictive Failure Deasserted'),
    '1770497': ('CablePredictiveFailureAsserted', 'INFORMATIONAL', 'Other Cable / Interconnect Event', 'Cable / Interconnect Predictive Failure Asserted'),
    '1797888': ('CableConnected', 'INFORMATIONAL', 'Other Cable / Interconnect Event', 'Cable/Interconnect is connected'),
    '1797889': ('ConfigurationError', 'INFORMATIONAL', 'Other Cable / Interconnect Event', 'Configuration Error'),
    '1798016': ('CableConnected', 'WARNING', 'Other Cable / Interconnect Event', 'Cable/Interconnect is disconnected'),
    '1798017': ('ConfigurationErrorCleared', 'INFORMATIONAL', 'Other Cable / Interconnect Event', 'Configuration Error Cleared'),
    '1835776': ('TerminatorStateDeasserted', 'INFORMATIONAL', 'Terminator Event', 'Terminator State Deasserted'),
    '1835777': ('TerminatorStateAsserted', 'INFORMATIONAL', 'Terminator Event', 'Terminator State Asserted'),
    '1836032': ('TerminatorPredictiveFailureDeasserted', 'INFORMATIONAL', 'Terminator Event', 'Terminator Predictive Failure Deasserted'),
    '1836033': ('TerminatorPredictiveFailureAsserted', 'INFORMATIONAL', 'Terminator Event', 'Terminator Predictive Failure Asserted'),
    '1928960': ('SystemBootByPowerUp', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart Initiated by power up'),
    '1928961': ('SystemBootByHardReset', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart Initiated by Hard Reset'),
    '1928962': ('SystemBootByWarmReset', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart Initiated by Warm Reset'),
    '1928963': ('UserRequestedPXEBoot', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart - User requested PXE boot'),
    '1928964': ('AutomaticDiagnosticBoot', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart - Automatic boot to diagnostic'),
    '1928965': ('OSInitiatedHardReset', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart - OS / run-time software initiated hard reset'),
    '1928966': ('OSInitiatedWarmReset', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart - OS / run-time software initiated Warm reset'),
    '1928967': ('SystemRestart', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart - Restart cause per Get System Restart Cause command'),
    '1929088': ('SystemBootByPowerUpDeasserted', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart Initiated by power up Deasserted'),
    '1929089': ('SystemBootByHardResetDeasserted', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart Initiated by Hard Reset Deasserted'),
    '1929090': ('SystemBootByWarmResetDeasserted', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart Initiated by Warm Reset Deasserted'),
    '1929091': ('UserRequestedPXEBootDeasserted', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart - User requested PXE boot Deasserted'),
    '1929092': ('AutomaticDiagnosticBootDeasserted', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart - Automatic boot to diagnostic Deasserted'),
    '1929093': ('OSInitiatedHardResetDeasserted', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart - OS / run-time software initiated hard reset Deasserted'),
    '1929094': ('OSInitiatedWarmReset', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart - OS / run-time software initiated Warm reset Deasserted'),
    '1929095': ('SystemRestart', 'INFORMATIONAL', 'System Boot / Restart Event', 'System Boot / Restart - Restart cause per Get System Restart Cause command Deasserted'),
    '1994496': ('NoBootableMedia', 'CRITICAL', 'Boot Error Event', 'Boot Error - No bootable media'),
    '1994497': ('NonBootableDisketteInDrive', 'CRITICAL', 'Boot Error Event', 'Boot Error - Non-bootable diskette left in drive'),
    '1994498': ('PXEServerNotFound', 'CRITICAL', 'Boot Error Event', 'Boot Error - PXE Server not found'),
    '1994499': ('InvalidBootSector', 'CRITICAL', 'Boot Error Event', 'Boot Error - Invalid boot sector'),
    '1994500': ('TimeoutWaitingUserSelection', 'INFORMATIONAL', 'Boot Error Event', 'Boot Error - Timeout waiting for user selection of boot source'),
    '1994624': ('FoundBootableMedia', 'INFORMATIONAL', 'Boot Error Event', 'Found bootable media'),
    '1994625': ('FoundBootableDisketteInDrive', 'INFORMATIONAL', 'Boot Error Event', 'Bootable diskette Found'),
    '1994626': ('PXEServerFound', 'INFORMATIONAL', 'Boot Error Event', 'PXE Server found'),
    '1994627': ('FoundValidBootSector', 'INFORMATIONAL', 'Boot Error Event', 'Found Valid boot sector'),
    '1994628': ('UserSelectedBootSource', 'INFORMATIONAL', 'Boot Error Event', 'User selected boot source'),
    '2060032': ('BootCompletedDirectoryA', 'INFORMATIONAL', 'OS Boot Event', 'A: boot completed'),
    '2060033': ('BootCompletedDirectoryC', 'INFORMATIONAL', 'OS Boot Event', 'C: boot completed'),
    '2060034': ('PXEBootCompleted', 'INFORMATIONAL', 'OS Boot Event', 'PXE boot completed'),
    '2060035': ('DiagnosticBootCompleted', 'INFORMATIONAL', 'OS Boot Event', 'Diagnostic boot completed'),
    '2060036': ('CDROMBootCompleted', 'INFORMATIONAL', 'OS Boot Event', 'CDROM boot completed'),
    '2060037': ('ROMBootCompleted', 'INFORMATIONAL', 'OS Boot Event', 'ROM boot completed'),
    '2060038': ('BootCompletedUnknownSource', 'INFORMATIONAL', 'OS Boot Event', 'Boot completed - boot device not specified'),
    '2060032': ('BootIncompleteDirectoryA', 'WARNING', 'OS Boot Event', 'A: boot incomplete'),
    '2060033': ('BootIncompleteDirectoryC', 'WARNING', 'OS Boot Event', 'C: boot incomplete'),
    '2060034': ('PXEBootIncomplete', 'WARNING', 'OS Boot Event', 'PXE boot Incomplete'),
    '2060035': ('DiagnosticBootIncomplete', 'WARNING', 'OS Boot Event', 'Diagnostic boot Incomplete'),
    '2060036': ('CDROMBootIncomplete', 'WARNING', 'OS Boot Event', 'CDROM boot Incomplete'),
    '2060037': ('ROMBootIncomplete', 'WARNING', 'OS Boot Event', 'ROM boot Incomplete'),
    '2060038': ('BootIncompleteUnknownSource', 'WARNING', 'OS Boot Event', 'Boot Incomplete - boot device not specified'),
    '2125568': ('OSStopDuringLoad', 'CRITICAL', 'OS Stop / Shutdown Event', 'OS Stop / Shutdown - Stop during OS load / initialization'),
    '2125569': ('OSRuntimeCriticalStop', 'CRITICAL', 'OS Stop / Shutdown Event', 'OS Stop / Shutdown - Run-time Critical Stop'),
    '2125570': ('OSGracefulStop', 'INFORMATIONAL', 'OS Stop / Shutdown Event', 'OS Stop / Shutdown - Graceful Stop'),
    '2125571': ('OSGracefulShutdown', 'INFORMATIONAL', 'OS Stop / Shutdown Event', 'OS Stop / Shutdown - Graceful Shutdown'),
    '2125572': ('OSSoftShutdownInitiatedByPEF', 'INFORMATIONAL', 'OS Stop / Shutdown Event', 'OS Stop / Shutdown - Soft Shutdown initiated by PEF'),
    '2125573': ('OSAgentNotResponding', 'CRITICAL', 'OS Stop / Shutdown Event', 'OS Stop / Shutdown - Agent Not Responding'),
    '2125696': ('OSStopDuringLoadDeasserted', 'INFORMATIONAL', 'OS Stop / Shutdown Event', 'OS Stop / Shutdown - Stop during OS load / initialization Deasserted'),
    '2125697': ('OSRuntimeINFORMATIONALStopDeasserted', 'INFORMATIONAL', 'OS Stop / Shutdown Event', 'OS Stop / Shutdown - Run-time INFORMATIONAL Stop Deasserted'),
    '2125698': ('OSGracefulStopDeasserted', 'INFORMATIONAL', 'OS Stop / Shutdown Event', 'OS Stop / Shutdown - Graceful Stop Deasserted'),
    '2125699': ('OSGracefulShutdownDeasserted', 'INFORMATIONAL', 'OS Stop / Shutdown Event', 'OS Stop / Shutdown - Graceful Shutdown Deasserted'),
    '2125700': ('OSSoftShutdownDeasserted', 'INFORMATIONAL', 'OS Stop / Shutdown Event', 'OS Stop / Shutdown - Soft Shutdown Deasserted'),
    '2125701': ('OSAgentNotRespondingDeasserted', 'INFORMATIONAL', 'OS Stop / Shutdown Event', 'OS Stop / Shutdown - Agent Started Responding'),
    '2191104': ('SlotFaultStatusAsserted', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Fault Status asserted'),
    '2191105': ('SlotIdentifyStatusAsserted', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Identify Status asserted'),
    '2191106': ('SlotDeviceInstalledOrAttached', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Device installed/attached'),
    '2191107': ('SlotReadyForDeviceInstallation', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Ready for Device Installation'),
    '2191108': ('SlotReadyForDeviceRemoval', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Ready for Device Removal'),
    '2191109': ('SlotPowerIsOff', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Slot Power is Off'),
    '2191110': ('SlotDeviceRemovalRequest', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Device Removal Request'),
    '2191111': ('SlotInterlockAsserted', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Interlock asserted'),
    '2191112': ('SlotDisabled', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Disabled'),
    '2191113': ('SlotHoldsSpareDevice', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - holds spare device'),
    '2191232': ('SlotFaultStatusDeasserted', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Fault Status Deasserted'),
    '2191233': ('SlotIdentifyStatusDeasserted', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Identify Status Deasserted'),
    '2191234': ('SlotDeviceRemoved', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Device Uninstalled/Removed'),
    '2191235': ('SlotNotReadyForDeviceInstallation', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Not Ready for Device Installation'),
    '2191236': ('SlotNotReadyForDeviceRemoval', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Ready for Device Removal'),
    '2191237': ('SlotPowerIsOn', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Slot Power is On'),
    '2191238': ('SlotDeviceRemovalRequestProcessed', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Device Removal Request Processed'),
    '2191239': ('SlotInterlockDeasserted', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Interlock Deasserted'),
    '2191240': ('SlotEnabled', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - Enabled'),
    '2191241': ('SlotFreesSpareDevice', 'INFORMATIONAL', 'Slot / Connector Event', 'Slot / Connector - frees spare device'),
    '2256640': ('ACPIStateS0Working', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - S0 / G0 '),
    '2256641': ('ACPIStateS1', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - S1'),
    '2256642': ('ACPIStateS2', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - S2 '),
    '2256643': ('ACPIStateS3', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - S3 - sleeping, processor & h/w context lost, memory retained'),
    '2256644': ('ACPIStateS4', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - S4'),
    '2256645': ('ACPIStateS5', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - S5 / G2'),
    '2256646': ('ACPIStateS4OrS5SoftOff', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - S4 / S5 soft-off'),
    '2256647': ('ACPIStateG3', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - G3'),
    '2256648': ('ACPISleepingInUnknownState', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - Sleeping in an S1, S2, or S3 states'),
    '2256649': ('ACPIStateG1', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - G1'),
    '2256650': ('ACPIStateS5ByOverride', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - S5 entered by override'),
    '2256651': ('ACPILegacyONState', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - Legacy ON state'),
    '2256652': ('ACPILegacyOFFState', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - Legacy OFF state'),
    '2256654': ('ACPIStateUnknown', 'INFORMATIONAL', 'System ACPI Power State Event', 'System ACPI Power State - Unknown'),
    '2322176': ('WatchdogTimerExpired', 'WARNING', 'Watchdog Event', 'Watchdog timer expired'),
    '2322177': ('WatchdogReset', 'CRITICAL', 'Watchdog Event', 'Watchdog Reset'),
    '2322178': ('WatchdogPowerDown', 'CRITICAL', 'Watchdog Event', 'Watchdog Power Down'),
    '2322184': ('WatchdogPowerCycle', 'WARNING', 'Watchdog Event', 'Watchdog Power cycle'),
    '2322304': ('WatchdogTimerInterrupt', 'INFORMATIONAL', 'Watchdog Event', 'Watchdog Timer interrupt'),
    '2322304': ('WatchdogTimerExpiredDeasserted', 'WARNING', 'Watchdog Event', 'Watchdog timer reset'),
    '2322305': ('WatchdogResetDeasserted', 'CRITICAL', 'Watchdog Event', 'Watchdog Reset Deasserted'),
    '2322306': ('WatchdogPowerDownDeasserted', 'CRITICAL', 'Watchdog Event', 'Watchdog Power Down Deasserted'),
    '2322307': ('WatchdogPowerCycleDeasserted', 'WARNING', 'Watchdog Event', 'Watchdog Power cycle Deasserted'),
    '2322312': ('WatchdogTimerInterruptDeasserted', 'INFORMATIONAL', 'Watchdog Event', 'Watchdog Timer interrupt Deasserted'),
    '2387712': ('PlatformGeneratedPage', 'INFORMATIONAL', 'Platform Alert Event', 'Platform Alert- platform generated page'),
    '2387713': ('PlatformGeneratedLANAlert', 'INFORMATIONAL', 'Platform Alert Event', 'Platform Alert- platform generated LAN alert'),
    '2387714': ('PlatformPETFormatTrap', 'INFORMATIONAL', 'Platform Alert Event', 'Platform Alert-  Platform Event Trap generated (formatted per IPMI PET specification)'),
    '2387715': ('PlatformOEMFormatTrap', 'INFORMATIONAL', 'Platform Alert Event', 'Platform Alert- platform generated SNMP trap, OEM format'),
    '2426880': ('EntityPresenceDeviceRemovedOrAbsent', 'CRITICAL', 'Entity Presence Event', 'A device is absent or has been removed.'),
    '2426881': ('EntityPresenceDeviceInsertedOrPresent', 'INFORMATIONAL', 'Entity Presence Event', 'A device is present or has been inserted.'),
    '2453248': ('EntityPresent', 'INFORMATIONAL', 'Entity Presence Event', 'Entity Present'),
    '2453249': ('EntityAbsent', 'INFORMATIONAL', 'Entity Presence Event', 'Entity Absent.'),
    '2453250': ('EntityDisabled', 'INFORMATIONAL', 'Entity Presence Event', 'Entity Disabled.'),
    '2491392': ('MonitoASICFailureDeasserted', 'INFORMATIONAL', 'Monitor ASIC / IC Event', 'Monitor ASIC / IC Failure Deasserted'),
    '2491393': ('MonitoASICFailureAsserted', 'MAJOR', 'Monitor ASIC / IC Event', 'Monitor ASIC / IC Failure Asserted'),
    '2649856': ('SensorAccessDegradedOrUnavailable', 'MAJOR', 'Management Subsystem Health Event', 'Sensor access degraded or unavailable'),
    '2649857': ('ControllerAccessDegradedOrUnavailable', 'MAJOR', 'Management Subsystem Health Event', 'Controller access degraded or unavailable'),
    '2649858': ('ManagementControllerOffline', 'MAJOR', 'Management Subsystem Health Event', 'Management controller off-line'),
    '2649859': ('ManagementControllerUnavailable', 'MAJOR', 'Management Subsystem Health Event', 'Management controller Unavailable'),
    '2649860': ('SensorFailure', 'MAJOR', 'Management Subsystem Health Event', 'Sensor failure'),
    '2649861': ('FRUFailure', 'MAJOR', 'Management Subsystem Health Event', 'FRU failure'),
    '2649984': ('SensorAccessAvailable', 'INFORMATIONAL', 'Management Subsystem Health Event', 'Sensor access Available'),
    '2649985': ('ControllerAccessAvailable', 'INFORMATIONAL', 'Management Subsystem Health Event', 'Controller access Available'),
    '2649986': ('ManagementControllerOnline', 'INFORMATIONAL', 'Management Subsystem Health Event', 'Management controller online'),
    '2649987': ('ManagementControllerAvailable', 'INFORMATIONAL', 'Management Subsystem Health Event', 'Management controller Available'),
    '2649988': ('SensorFailureDeasserted', 'INFORMATIONAL', 'Management Subsystem Health Event', 'Sensor failure Deasserted'),
    '2649989': ('FRUFailureDeasserted', 'INFORMATIONAL', 'Management Subsystem Health Event', 'FRU failure Deasserted'),
    '2715392': ('BatteryLowAssert', 'WARNING', 'Battery Event', 'Battery low'),
    '2715393': ('BatteryFailed', 'CRITICAL', 'Battery Event', 'Battery Failed'),
    '2715394': ('BatteryPresenceDetected', 'INFORMATIONAL', 'Battery Event', 'Battery presence detected'),
    '2780928': ('SessionActivated', 'INFORMATIONAL', 'Session Audit Event', 'Session Activated'),
    '2780929': ('SessionDeactivated', 'WARNING', 'Session Audit Event', 'Session Deactivated'),
    '2780930': ('SessionInvalidUsernameOrPassword', 'WARNING', 'Session Audit Event', 'Session Invalid Username or Password'),
    '2780931': ('SessionInvalidUsernameOrPassword', 'WARNING', 'Session Audit Event', 'Session Invalid password disable'),
    '2846464': ('HardwareVersionChangeDetected', 'INFORMATIONAL', 'Version Change Event', 'Hardware Version change detected'),
    '2846465': ('FirmwareOrSoftwareVersionChangeDetected', 'INFORMATIONAL', 'Version Change Event', 'Firmware or Software version change detected'),
    '2846466': ('HardwareVersionIncombabailityDetected', 'INFORMATIONAL', 'Version Change Event', 'Hardware Incombabaility detected'),
    '2846467': ('FirmwareOrSoftwareVersionIncompatibilityDetected', 'INFORMATIONAL', 'Version Change Event', 'Firmware Or SoftwareVersion Incompatibility detected'),
    '2846468': ('EntityInvalidOrUnsupportedHardware', 'INFORMATIONAL', 'Version Change Event', 'Entity is of an invalid or unsupported hardware version'),
    '2846469': ('EntityInvalidOrUnsupportedSwOrFw', 'INFORMATIONAL', 'Version Change Event', 'Entity contains an invalid or unsupported firmware or software version'),
    '2846470': ('HardwareChangeSuccessful', 'INFORMATIONAL', 'Version Change Event', 'Hardware Change detected with associated Entity was successful'),
    '2846471': ('SwOrFwChangeSuccessful', 'INFORMATIONAL', 'Version Change Event', 'Software or F/W Change detected with associated Entity was successful.'),
    '2846598': ('HardwareChangeNotSuccessful', 'INFORMATIONAL', 'Version Change Event', 'Hardware Change detected with associated Entity was not successful'),
    '2846599': ('SwOrFwChangeNotSuccessful', 'INFORMATIONAL', 'Version Change Event', 'Software or F/W Change detected with associated Entity was not successful.'),
    '2912000': ('FRUNotInstalled', 'INFORMATIONAL', 'FRU State Event', 'FRU Not Installed'),
    '2912001': ('FRUInactive', 'INFORMATIONAL', 'FRU State Event', 'FRU Inactive'),
    '2912002': ('FRUActivationRequested', 'INFORMATIONAL', 'FRU State Event', 'FRU Activation Requested'),
    '2912003': ('FRUActivationInProgress', 'INFORMATIONAL', 'FRU State Event', 'FRU Activation In Progress'),
    '2912004': ('FRUActive', 'INFORMATIONAL', 'FRU State Event', 'FRU Active'),
    '2912005': ('FRUDeactivationRequested', 'INFORMATIONAL', 'FRU State Event', 'FRU Deactivation Requested'),
    '2912006': ('FRUDeactivationInProgress', 'INFORMATIONAL', 'FRU State Event', 'FRU Deactivation In Progress'),
    '2912007': ('FRUCommunicationLost', 'INFORMATIONAL', 'FRU State Event', 'FRU Communication Lost'),
    '12611586': ('OverTemperatureNonRecoverableHigh', 'CRITICAL', 'Temperature Event', 'Under-Temperature Warning (overheat, going high)'),
    '12611714': ('OverTemperatureNonRecoverableHigh', 'CRITICAL', 'Temperature Event', 'Under-Temperature Warning (overheat, going high) cleared'),

}

# Decode specific trap number:
#  31:24 - reserved
#  23:16 - event sensor type eg. Temperature           -> resource eg. Temperature#0x40 and event eg. TemperatureEvent
#  15:8  - event type eg. Sensor specific threshold    -> thresholdInfo eg. 'Sensor Specific - ...'
#     7  - event direction eg. assertion/de-assertion
#   6:4  - reserved
#   3:0  - event offset value ie. up to 15 discrete events per event type

# Decode PET hex payload
#  19:22 - local time                                   -> createTime
#     25 - trap source type (almost always IPMI)        -> tags eg. 'BIOS Vendor'
#     26 - event source type (almost always IPMI)       -> tags eg. 'IPMI'
#     27 - event severity                               -> value eg. 'Non-critical condition'
#     28 - sensor device
#     29 - sensor number                                -> resource eg. 'Memory#0x50'
#     30 - entity id                                    -> tags eg. 'cooling unit'
#     31 - entity instance
#  32:39 - event data
#   last - 'C1'

# SNMP MIB TRAP-TYPES
# trapnum - trap-name (not used), severity, trap-type (not used), text

trapnum = int(trapvars['$q'])
if trapnum:
    LOG.debug('event_sensor_type=%s, event_type=%s, event_direction=%s, event_offset=%s',
              (trapnum & 0xff0000) >> 16, (trapnum & 0xff00) >> 8, (trapnum & 0x80), (trapnum & 0xf))
else:
    LOG.error('Error decoding trap number - has the SMT PET Event Trap mib been accidentally loaded?')  # loading the mib will mean the specific trap number is not available for decoding

octet = ['00'] + varbinds['PET-EVENTS::petevts.1'].replace('\n', '').replace('"', '').rstrip(' ').split(' ')  # zero-pad so that array indices match IPMI spec
if octet[-1] != 'C1':
    LOG.error('Error decoding IPMI Platform Event Trap: %s', octet)
else:
    LOG.debug('trap_source_type=%s, event_source_type=%s, event_severity=%s, sensor_device=%s, sensor_number=%s, '
              'entity_id=%s, entity_instance=%s, event_data=%s%s%s',
              octet[25], octet[26], octet[27], octet[28], octet[29], octet[30], octet[31], octet[32], octet[33], octet[34])

sensor_type = (trapnum & 0xff0000) >> 16
sensor_number = octet[29]
resource = '%s:%s#0x%s' % (resource, SENSOR_TYPE_MAP.get(sensor_type, 'Unknown'), sensor_number)
event = '%sEvent' % SENSOR_TYPE_MAP.get(sensor_type, 'Unknown')

event_severity = octet[27]
value = PET_SEVERITY.get(event_severity)

event_type = (trapnum & 0xff00) >> 8
if event_type <= 0x0B:
    event_type = 'Generic'
elif event_type == 0x6F:
    event_type = 'Sensor Specific'
elif 0x70 <= event_type <= 0x7F:
    event_type = 'OEM'
else:
    event_type = 'reserved'
threshold_info = event_type

local_timestamp = (int(octet[19], 16) << 24) + (int(octet[20], 16) << 16) + (int(octet[21], 16) << 8) + int(octet[22], 16)
create_time = datetime.datetime(1998, 1, 1) + datetime.timedelta(seconds=local_timestamp)

trap, severity, trap_type, text = PET_EVENT_TRAPNUM[trapvars['$q']]
severity = severity.lower()

entity_id = octet[30]
tags.append(ENTITY_ID_MAP.get(entity_id, None))

event_direction = 'assert' if not (trapnum & 0x80) else 'deassert'
threshold_info = '%s - %s' % (PET_SEVERITY.get(octet[27], None), event_direction)

trap_source_type_code = int(octet[25], 16)
event_source_type_code = int(octet[26], 16)

for trap_source_type in PET_SOURCE_TYPE:
    if trap_source_type_code < PET_SOURCE_TYPE[trap_source_type]:
        break
tags.append(trap_source_type)

# for event_source_type in PET_SOURCE_TYPE:
#     if event_source_type_code < PET_SOURCE_TYPE[event_source_type]:
#         break
# tags.append(event_source_type)
